Update dockerfiles

diff --git a/Dockerfile.freyja_apps.arm64 b/Dockerfile.freyja_apps.arm64
--- a/Dockerfile.freyja_apps.arm64
+++ b/Dockerfile.freyja_apps.arm64
@@ -29,12 +29,13 @@ RUN /sdv/container/scripts/argument_sanitizer.sh \
     --regex "^[a-zA-Z_0-9-]+$" || \
     ( echo "Argument sanitizer failed for ARG 'APP_NAME'"; exit 1 )
 
-# Check that CONFIG_PATH argument is valid if it is not empty.
-RUN [ -z "${CONFIG_PATH}" ] || \
-    /sdv/container/scripts/argument_sanitizer.sh \
-    --arg-value "${CONFIG_PATH}" \
-    --regex "^[.\/a-zA-Z_0-9-]+$" || \
-    ( echo "Argument sanitizer failed for ARG 'CONFIG_PATH'"; exit 1 )
+# Check that CONFIG_PATH argument is valid if it's non-empty.
+RUN if [ -n "${CONFIG_PATH}" ]; then \
+        /sdv/container/scripts/argument_sanitizer.sh \
+        --arg-value "${CONFIG_PATH}" \
+        --regex "^[.\/a-zA-Z_0-9-]+$" || \
+        ( echo "Argument sanitizer failed for ARG 'CONFIG_PATH'"; exit 1 ); \
+    fi
 
 # Add Build dependencies.
 RUN apt update && apt upgrade -y && apt install -y \
@@ -106,6 +107,7 @@ WORKDIR /sdv
 
 # Copy the executable from the "build" stage.
 COPY --from=build /sdv/service /sdv/
+# Copy the build directory so that we can access the necessary configuration files from the out_dir
 COPY --from=build /sdv/target/aarch64-unknown-linux-gnu/release/build/ /sdv/target/aarch64-unknown-linux-gnu/release/build/
 
 # Copy from config override directory into where Freyja expects it
